#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

case "$1" in
  help | minio:help)
    help_content_func () {
      declare desc="return help_content string"
      cat<<help_content
      objectstore:create <service>, creates an objectstore service
      objectstore:enter <service>, drops you in a shell where you can explore data in the service store
      objectstore:destroy <service>, destroys an objectstore service
      objectstore:link <service> <app>, links an app to the objectstore service                
      objectstore:enter <service>, drops you in a bash session in the service container
      objectstore:exists <service>, checks if a service exists
      objectstore:start <service>, starts the service container                     
      objectstore:restart <service>,  gracefully shuts down and restarts the service container               
      objectstore:stop <service>, gracefully shuts down the service container     
help_content
    }

    if [[ $1 = "objectstore:help" ]] ; then
        echo -e 'Usage: dokku objectstore<:command> [...other]]'
        echo ''
        echo 'Additional commands:'
        help_content_func | sort | column -c2 -t -s,
    else
        help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac