#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common-functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
if [[ -f "$PLUGIN_AVAILABLE_PATH/docker-options/functions" ]]; then
  source "$PLUGIN_AVAILABLE_PATH/docker-options/functions"
fi

is_valid_service_name() {
  declare desc="validate a service name"
  declare SERVICE="$1"
  [[ -z "$SERVICE" ]] && return 1

  if [[ "$SERVICE" =~ ^[A-Za-z0-9_-]+$ ]]; then
    return 0
  fi

  return 1
}

service_create_container() {
  local SERVICE="$1"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_HOST_ROOT="$PLUGIN_DATA_HOST_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local ACCESS_KEY="$(service_access_key "$SERVICE")"
  local SECRET_KEY="$(service_secret_key "$SERVICE")"
  local ROOT_USER="$(service_root_user "$SERVICE")"
  local ROOT_PASSWORD="$(service_root_password "$SERVICE")"

  local DATABASE_NAME="$(get_database_name "$SERVICE")"
  local PREVIOUS_ID

  if [[ -f "$SERVICE_ROOT/CONFIG_OPTIONS" ]]; then
    export CONFIG_OPTIONS="$(cat "$SERVICE_ROOT/CONFIG_OPTIONS")"
  fi

  [[ -f "$SERVICE_ROOT/SERVICE_MEMORY" ]] && SERVICE_MEMORY="$(cat "$SERVICE_ROOT/SERVICE_MEMORY")"
  if [[ -n "$SERVICE_MEMORY" ]]; then
    MEMORY_LIMIT="--memory=${SERVICE_MEMORY}m"
  fi

  [[ -f "$SERVICE_ROOT/SHM_SIZE" ]] && SERVICE_SHM_SIZE="$(cat "$SERVICE_ROOT/SHM_SIZE")"
  if [[ -n "$SERVICE_SHM_SIZE" ]]; then
    SHM_SIZE="--shm-size=${SERVICE_SHM_SIZE}"
  fi

  [[ -f "$SERVICE_ROOT/IMAGE" ]] && PLUGIN_IMAGE="$(cat "$SERVICE_ROOT/IMAGE")"
  [[ -f "$SERVICE_ROOT/IMAGE_VERSION" ]] && PLUGIN_IMAGE_VERSION="$(cat "$SERVICE_ROOT/IMAGE_VERSION")"

  # shellcheck disable=SC2086
  ID=$(docker run --name "$SERVICE_NAME" \
    $MEMORY_LIMIT $SHM_SIZE \
    -v "$SERVICE_HOST_ROOT/data:/var/lib/minio/data" \
    -e "MINIO_ROOT_USER=$ROOT_USER" \
    -e "MINIO_ROOT_PASSWORD=$ROOT_PASSWORD" \
    --env-file="$SERVICE_ROOT/ENV" \
    -d --restart always \
    --label dokku=service \
    --label dokku.service=minio \
    "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" \
    $CONFIG_OPTIONS \
    server /var/lib/minio/data --address ":${PLUGIN_DATASTORE_PORTS[0]}" --console-address ":${PLUGIN_DATASTORE_PORTS[1]}")
  echo "$ID" >"$SERVICE_ROOT/ID"

  dokku_log_verbose_quiet "Waiting for container to be ready"
  docker run --rm --link "$SERVICE_NAME:$PLUGIN_COMMAND_PREFIX" "$PLUGIN_WAIT_IMAGE" -p "$PLUGIN_DATASTORE_WAIT_PORT" >/dev/null

  dokku_log_verbose_quiet "Setting up user"
  local TARGET_IP_ADDRESS="$(docker inspect $ID --format '{{ .NetworkSettings.IPAddress }}')"
  docker run --rm --link "$SERVICE_NAME:$PLUGIN_COMMAND_PREFIX" \
    -e "MC_HOST_$SERVICE_NAME=http://${ROOT_USER}:${ROOT_PASSWORD}@${TARGET_IP_ADDRESS}:${PLUGIN_DATASTORE_PORTS[0]}" \
    --entrypoint=/bin/sh "$PLUGIN_MINIO_CLIENT_IMAGE" \
    -c "
    mc admin user add $SERVICE_NAME $ACCESS_KEY $SECRET_KEY;
    mc admin policy set $SERVICE_NAME readwrite user=$ACCESS_KEY
    " > /dev/null

  dokku_log_verbose_quiet "Securing connection to database"
#   service_stop "$SERVICE" >/dev/null
#   docker run --rm -i -v "$SERVICE_HOST_ROOT/data:/var/lib/minio/data" "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" bash -s <"$(cd "$(dirname "${BASH_SOURCE[0]}") && pwd)/scripts/enable_ssl.sh" &>/dev/null

#   PREVIOUS_ID=$(docker ps -aq --no-trunc --filter "status=exited" --filter "name=^/$SERVICE_NAME$" --format '{{ .ID }}') || true
#   docker start "$PREVIOUS_ID" >/dev/null
#   service_port_unpause "$SERVICE"

  dokku_log_info2 "$PLUGIN_SERVICE container created: $SERVICE"
  service_info "$SERVICE"
}

service_create() {
  local SERVICE="$1"
  is_valid_service_name "$SERVICE" || dokku_log_fail "Please specify a valid name for the service. Valid characters are: [A-Za-z0-9_]+"
  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a valid name for the service"
  [[ ! -d "$PLUGIN_DATA_ROOT/$SERVICE" ]] || dokku_log_fail "$PLUGIN_SERVICE service $SERVICE already exists"
  SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  LINKS_FILE="$SERVICE_ROOT/LINKS"

  service_parse_args "${@:2}"

  if ! service_image_exists "$SERVICE"; then
    if [[ "$PLUGIN_DISABLE_PULL" == "true" ]]; then
      dokku_log_warn "${PLUGIN_DISABLE_PULL_VARIABLE} environment variable detected. Not running pull command." 1>&2
      dokku_log_warn "   docker pull ${IMAGE}" 1>&2
      dokku_log_warn "$PLUGIN_SERVICE service creation failed"
      exit 1
    fi
    docker pull "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" || dokku_log_fail "$PLUGIN_SERVICE image $PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION pull failed"
  fi

  plugn trigger service-action pre-create "$PLUGIN_COMMAND_PREFIX" "$SERVICE"
  mkdir -p "$SERVICE_ROOT" || dokku_log_fail "Unable to create service directory"
  mkdir -p "$SERVICE_ROOT/data" || dokku_log_fail "Unable to create service data directory"
  touch "$LINKS_FILE"

  
  SECRET_KEY=$(openssl rand -hex 16)
  ACCESS_KEY=$(openssl rand -hex 16)
  ROOT_USER=$(openssl rand -hex 16)
  ROOT_PASSWORD=$(openssl rand -hex 16)
  if [[ -n "$ROOT_USER" ]]; then
    ACCESS_KEY="$ACCESS_KEY"
    dokku_log_warn "Specified access key may not be as secure as the auto-generated password"
  fi
  if [[ -n "$SERVICE_SECRET_KEY" ]]; then
    SECRET_KEY="$SERVICE_SECRET_KEY"
    dokku_log_warn "Specified secret key may not be as secure as the auto-generated password"
  fi
  if [[ -n "$ROOT_USER" ]]; then
    SECRET_KEY="$ROOT_USER"
    dokku_log_warn "Specified root user may not be as secure as the auto-generated password"
  fi
  if [[ -n "$ROOT_PASSWORD" ]]; then
    SECRET_KEY="$ROOT_PASSWORD"
    dokku_log_warn "Specified root password may not be as secure as the auto-generated password"
  fi

  echo "$ACCESS_KEY" > "$SERVICE_ROOT/ACCESS_KEY"
  chmod 640 "$SERVICE_ROOT/ACCESS_KEY"
  echo "$SECRET_KEY" > "$SERVICE_ROOT/SECRET_KEY"
  chmod 640 "$SERVICE_ROOT/SECRET_KEY"
  echo "$ROOT_PASSWORD" > "$SERVICE_ROOT/ROOTPASSWORD"
  chmod 640 "$SERVICE_ROOT/ROOTPASSWORD"
  echo "$ROOT_USER" > "$SERVICE_ROOT/ROOTUSER"
  chmod 640 "$SERVICE_ROOT/ROOTUSER"

  service_commit_config "$SERVICE"
  write_database_name "$SERVICE"
  plugn trigger service-action post-create "$PLUGIN_COMMAND_PREFIX" "$SERVICE"
  service_create_container "$SERVICE"
  plugn trigger service-action post-create-complete "$PLUGIN_COMMAND_PREFIX" "$SERVICE"
}

service_start() {
  local SERVICE="$1"
  local QUIET="$2"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local ID=$(docker ps -aq --no-trunc --filter "status=running" --filter "name=^/$SERVICE_NAME$" --format '{{ .ID }}') || true
  if [[ -n $ID ]]; then
    [[ -z $QUIET ]] && dokku_log_warn "Service is already started"
    if [[ ! -f "$SERVICE_ROOT/ID" ]] || [[ "$(cat "$SERVICE_ROOT/ID")" != "$ID" ]]; then
      [[ -z $QUIET ]] && dokku_log_warn "Updating local container ID"
      echo "$ID" >"$SERVICE_ROOT/ID"
    fi
    return 0
  fi

  dokku_log_info2_quiet "Starting container"
  local PREVIOUS_ID=$(docker ps -aq --no-trunc --filter "status=exited" --filter "name=^/$SERVICE_NAME$" --format '{{ .ID }}') || true
  local PASSWORD="$(service_password "$SERVICE")"

  if [[ -n $PREVIOUS_ID ]]; then
    docker start "$PREVIOUS_ID" >/dev/null
    service_port_unpause "$SERVICE"
    dokku_log_info2 "Container started"
  elif service_image_exists "$SERVICE" && [[ -n "$PASSWORD" ]]; then
    service_create_container "$SERVICE"
  else
    if ! service_image_exists "$SERVICE"; then
      [[ -f "$SERVICE_ROOT/IMAGE" ]] && PLUGIN_IMAGE="$(cat "$SERVICE_ROOT/IMAGE")"
      [[ -f "$SERVICE_ROOT/IMAGE_VERSION" ]] && PLUGIN_IMAGE_VERSION="$(cat "$SERVICE_ROOT/IMAGE_VERSION")"
      dokku_log_verbose_quiet "Missing image $PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION for $SERVICE"
    else
      dokku_log_verbose_quiet "Neither container nor valid configuration exists for $SERVICE"
    fi
  fi
}

service_connect() {
  local SERVICE="$1"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local ACCESS_KEY="$(service_access_key "$SERVICE")"
  local SECRET_KEY="$(service_secret_key "$SERVICE")"

  local SERVICE_NAME="$(get_service_name "$SERVICE")"
  local DATABASE_NAME="$(get_database_name "$SERVICE")"
  local ID=$(cat $SERVICE_ROOT/ID)

  TMPDIR=$(mktemp -d --tmpdir)
  trap 'rm -rf "$TMPDIR" > /dev/null' RETURN INT TERM EXIT

  echo "
  export SHELL=/bin/bash
  export PS1=\"\e[0;32m mc ($SERVICE_NAME)> \e[0m\";
  alias ls='mc ls "$SERVICE_NAME"'
  alias cp='mc cp "$SERVICE_NAME"'
  alias cat='mc cat $SERVICE_NAME'
  mb() { 'mc mb "$SERVICE_NAME/\$1" }
  alias pipe='mc pipe "$SERVICE_NAME"'
  alias find='mc find "$SERVICE_NAME"'
  alias tree='mc tree "$SERVICE_NAME"'
  mc --quiet --autocompletion > /dev/null
  " > $TMPDIR/.bashrc

  echo "
  For convenience, ls, cp, cat, mkdir, pipe, find, tree have been aliased to run \'mc <command> ${SERVICE_NAME}\'\n
  See https://docs.min.io/docs/minio-client-complete-guide for more commands
  " > $TMPDIR/issue

  local SERVICE_TTY_OPTS
  has_tty && SERVICE_TTY_OPTS="-t"

  local TARGET_IP_ADDRESS="$(docker inspect $ID --format '{{ .NetworkSettings.IPAddress }}')"
  docker run --rm --link "$SERVICE_NAME:$PLUGIN_COMMAND_PREFIX" \
    --env=LANG=C.UTF-8 --env=LC_ALL=C.UTF-8 -i $SERVICE_TTY_OPTS \
    -e "MC_HOST_$SERVICE_NAME=http://${ACCESS_KEY}:${SECRET_KEY}@${TARGET_IP_ADDRESS}:${PLUGIN_DATASTORE_PORTS[0]}" \
    --entrypoint=/bin/bash \
    -v $TMPDIR/issue:/etc/issue \
    -v $TMPDIR/.bashrc:/root/.bashrc \
    "$PLUGIN_MINIO_CLIENT_IMAGE"
}